Updated designs
hackmcgill/mchacks11 pull request #12
Opened 2023-12-02 03:32 UTC by MikaVohl

### List of changes:

- Added new logo
- Updated favicon
- Added new FAQ design
- Added new images and removed boxes for About and Sponsor
- Added "and more coming soon" code and commented it out for sponsors
- Added more color blurs

### Type of change:

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] New release
- [ ] Requires a documentation update

2023-12-05 17:10 UTC, jackyyzhang03 requested changes
On smaller screen sizes, faq content can overflow

<img width="1098" alt="Screen Shot 2023-12-05 at 12 09 04 PM" src="https://github.com/hackmcgill/mchacks11/assets/81784897/c2fd9ed5-de1a-48a2-ab5f-2efbc4926faa">

2023-12-05 17:14 UTC, jackyyzhang03 commented on package.json
> +    "use-resize-observer": "^9.1.0"
Did we end up using this package?

2023-12-05 17:19 UTC, jackyyzhang03 commented
There appear to be some gaps that shouldn't be there

![Screen Shot 2023-12-05 at 12 02 58 PM](https://github.com/hackmcgill/mchacks11/assets/81784897/73c415e8-057b-4901-9b1d-f521c07d6ba7)

2023-12-06 01:21 UTC, MikaVohl commented on package.json
> +    "use-resize-observer": "^9.1.0"
No we didn't, I just uninstalled it for the next commit

2024-01-19 21:12 UTC, jackyyzhang03 approved these changes
LGTM

2024-01-19 21:13 UTC, merged